### ISSUE TITLE
可以讲一下，这个插件添加并启动以后怎么使用吗

### ISSUE THREAD

**Issue by 73410** [itzdrli/koishi-plugin-mc-server-status#3]

**Comment by itzdrli** [comment]
提供一下环境信息（点击图中Koishi字样即可复制）
![image](https://github.com/itzdrli/koishi-plugin-mc-server-status/assets/52338732/6384a928-bcf9-4f52-a1f7-a80782058c1f)

**Comment by 73410** [comment]
![image](https://github.com/itzdrli/koishi-plugin-mc-server-status/assets/101000135/f4dd40af-1c91-4e0f-bdac-b391e065c22e)

**Comment by 73410** [comment]
![image](https://github.com/itzdrli/koishi-plugin-mc-server-status/assets/101000135/e9425341-4bd3-4070-85bd-cc9a972236d2)

**Comment by itzdrli** [comment]
> ![image](https://user-images.githubusercontent.com/101000135/260991012-e9425341-4bd3-4070-85bd-cc9a972236d2.png)

升级你的NodeJS版本到18+，readme里写的很清楚只支持NodeJS 18+

**Comment by 73410** [comment]
能不能问下怎么更改koishi的node版本

**Comment by itzdrli** [comment]
> 

使用问题/NodeJS基础常识不予解答，自行百度搜索NodeJS更新

**Comment by 73410** [comment]
主要是这个node是koishi自带的，根本找不到上面的弄的具体在哪里，直接下一个新版node也没法把koishi设置成使用外部的node
